name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
            # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - uses: pnpm/action-setup@v2
        with:
          version: 8


      # Run CI
      - run: pnpm i --frozen-lockfile

      - uses: nrwl/nx-set-shas@v4
      - run: pnpm biome check --changed --since=${{ env.NX_BASE }} --files-ignore-unknown=true
      - run: pnpm nx affected -t test build
